white_list_words = [
    "place",
    "mark",
    "invoice",
    "part",
    "tariff",
    "quantity",
    "packages",
    "description",
    "information",
    "gross",
    "class",
    "hazmat",
    "commodity",
    "package",
    "pallet",
    "value",
    "marks",
    "piece",
    "pieces",
    "type",
    "parties",
    "order",
    "volume",
    "weight",
    "numeric",
    "division",
    "item",
    "shipping",
    "product",
    "slip",
    "batch",
    "partial",
    "expiration",
    "unit",
    "details",
    "measurement",
    "count",
    "nature",
    "container",
    "price",
    "rate",
    "charge",
    "packaging",
    "group",
    "ordered",
    "packs",
    "goods",
    "amount",
    "hash",
    "chargeable",
    "tons",
    "total",
    "serial",
    "descending",
]

# black listed black_list_words --
# invoice,quantity, weight,price, amount,total, details, goods, unit, date, gross., net, volumn, inch, feet,carton,cartons, pieces,tax, discount,subtotal

# black_list_words_ =   ["indole", "intone", "insole"],
#     ["clastic", "quality", "quantify"],
#     ["wright", "veldt", "veiny"],
#     ["nice", "lidice", "pice", "clarice", "prig"],
#     ["annuitant", "mount", "unionist", "anouilh"],
#     ["tonal", "toil", "laius", "talo", "talos", "tola", "loyal"],
#     ["derails", "detains", "dovetails", "deimos", "tetanus"],
#     ["gooks", "poods", "goads", "goons", "roods"],
#     ["unfits", "numis", "tinct", "unite", "nits"],
#     ["idem", "lief"],
#     ["rate", "crate", "dele", "dole", "dote", "orate"],
# ['grass',  'gloss', 'cross', 'dross', 'groks','coss'],
# [ "piet", "icel", "nat","met"],[  "column","volition"],["incr",  "titch"],['fret', 'feer','feel'],[  "colon","conrail",  "carlin",  "carlota"],[  "carton",
#   "colon",  "contains",  "calais",  "carloads"],["nieces","flexes"],[  "lox",
#   "fax"],["viscount"],,[  "subsoil",
#   "nucleolar"]]

# black_list_words = [item for sublist in black_list_words for item in sublist]
black_list_words = [
    "indole",
    "intone",
    "insole",
    "clastic",
    "quantify",
    "wright",
    "veldt",
    "veiny",
    "prick",
    "nice",
    "noe",
    "pice",
    "clarice",
    "prig",
    "mount",
    "anouilh",
    "unionist",
    "toil",
    "laius",
    "talo",
    "talos",
    "tola",
    "loyal",
    "derails",
    "detains",
    "dovetails",
    "retails",
    "tetanus",
    "poods",
    "gooks",
    "goads",
    "goons",
    "roods",
    "hoods",
    "foods",
    "unfits",
    "Uniats",
    "numis",
    "tinct",
    "unite",
    "nits",
    "idem",
    "lief",
    "rate",
    "crate",
    "dele",
    "dole",
    "dote",
    "orate",
    "grass",
    "gloss",
    "cross",
    "dross",
    "groks",
    "coss",
    "piet",
    "flexes" "icel",
    "nat",
    "met",
    "column",
    "volition",
    "fret",
    "feer",
    "feel",
    "incr",
    "titch",
    "colon",
    "conrail",
    "carlin",
    "carlota",
    "carton",
    "contains",
    "calais",
    "carloads",
    "nieces",
    "lox",
    "fax",
    "viscount",
    "subsoil",
    "nucleolar",
]
